Added CLI option to delete a project
OctopusDeploy/OctopusCLI pull request #177
Opened 2022-05-10 15:33 UTC by milanmayr

I needed to delete projects systematically, but I had no option to do this. So, I extended the CLI to include a `delete-project` command. I was able to build the solution, and I tested the MacOS executable, successfully deleting a project.

2022-06-08 01:40 UTC, slewis74 requested changes
Thank you for your contribution and apologies for the delay in getting to the review. Overall this is looks fine. There are a couple of minor cleanup things and one adjustment to the exception control flow that we'd request.

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DisableProjectCommand.cs
> +        public bool ProjectExists { get; set; }
```suggestion
```
Remove unused properties

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DeleteProjectCommand.cs
> +        public bool ProjectExists { get; set; }
```suggestion
```
Remove unused properties

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DeleteProjectCommand.cs
> +                    ProjectDeleted = ProjectDeleted
```suggestion
                    ProjectDeleted
```
remove redundant assignment

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DeleteProjectCommand.cs
> +                throw new CommandException($"The project {project.Name} does not exist.");
```suggestion
                throw new CouldNotFindException("project");
```

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DisableProjectCommand.cs
> +                throw new CommandException($"The project {project.Name} does not exist.");
```suggestion
                throw new CouldNotFindException("project");
```

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DisableProjectCommand.cs
> +                throw new CommandException($"The project {project.Name} is already disabled.");
```suggestion
```

2022-06-08 01:40 UTC, slewis74 commented on source/Octopus.Cli/Commands/Project/DeleteProjectCommand.cs
> +                ProjectDeleted = false;
```suggestion
```

2022-06-09 05:44 UTC, milanmayr commented
@slewis74 thanks for the review! Your suggestions were really helpful, and I incorporated all of them.

I also imported a namespace so those new Exception types would be recognized.

2022-06-14 04:36 UTC, slewis74 approved these changes
👍

2022-06-17 01:45 UTC, merged

2022-06-17 06:50 UTC, slewis74 commented
Just a heads up, we've been doing some renovations to the build/deploy pipeline for the CLI over the last week or so. There was a glitch with `9.0.0` but these changes have been shipped in `9.1.1`.